name: ngs-pipeline
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - aioeasywebdav=2.4.0=py36_1000
  - aiohttp=3.6.2=py36h516909a_0
  - appdirs=1.4.3=py_1
  - async-timeout=3.0.1=py_1000
  - attrs=19.3.0=py_0
  - bcrypt=3.1.7=py36h516909a_0
  - boto3=1.10.45=py_0
  - botocore=1.13.45=py_0
  - bwa=0.7.17=hed695b0_6
  - bzip2=1.0.8=h516909a_2
  - ca-certificates=2019.11.28=hecc5488_0
  - cachetools=3.1.1=py_0
  - cairo=1.16.0=hfb77d84_1002
  - certifi=2019.11.28=py36_0
  - cffi=1.13.2=py36h8022711_0
  - chardet=3.0.4=py36_1003
  - click=7.0=py_0
  - coloredlogs=10.0=py36_1000
  - colormath=3.0.0=py_2
  - configargparse=0.13.0=py_1
  - cryptography=2.8=py36h72c5cf5_1
  - curl=7.65.3=hf8cf82a_0
  - cycler=0.10.0=py_2
  - datrie=0.8=py36h516909a_0
  - dbus=1.13.6=he372182_0
  - decorator=4.4.1=py_0
  - docutils=0.15.2=py36_0
  - dropbox=9.4.0=py_0
  - expat=2.2.5=he1b5a44_1004
  - fastqc=0.11.8=2
  - fftw=3.3.8=nompi_h7f3a6c3_1110
  - filechunkio=1.6=py36_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=2.001=hab24e00_0
  - font-ttf-source-code-pro=2.030=hab24e00_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.13.1=h86ecdb6_1001
  - fonts-conda-forge=1=0
  - freetype=2.10.0=he983fc9_1
  - fribidi=1.0.5=h516909a_1002
  - ftputil=3.2=py36_0
  - future=0.18.2=py36_0
  - gatk4=4.1.4.1=1
  - gdk-pixbuf=2.32.2=1
  - gettext=0.19.8.1=hc5be6a0_1002
  - ghostscript=9.18=1
  - giflib=5.1.7=h516909a_1
  - gitdb2=2.0.6=py_0
  - gitpython=3.0.5=py_0
  - glib=2.58.3=py36h6f030ca_1002
  - gobject-introspection=1.58.2=py36h5503ade_1002
  - google-api-core=1.15.0=py36_0
  - google-auth=1.10.0=py_0
  - google-cloud-core=1.1.0=py_0
  - google-cloud-storage=1.20.0=py_0
  - google-resumable-media=0.4.1=py_0
  - googleapis-common-protos=1.6.0=py36_0
  - graphite2=1.3.13=hf484d3e_1000
  - graphviz=2.42.3=h0511662_0
  - gst-plugins-base=1.14.5=h0935bb2_0
  - gstreamer=1.14.5=h36ae1b5_0
  - harfbuzz=2.4.0=h9f30f68_3
  - htslib=1.9=h4da6232_3
  - humanfriendly=4.18=py36_0
  - icu=64.2=he1b5a44_1
  - idna=2.8=py36_1000
  - idna_ssl=1.1.0=py36_1000
  - imagemagick=7.0.9_10=pl526h5b29c3e_0
  - importlib_metadata=1.3.0=py36_0
  - jbig=2.1=h14c3975_2001
  - jinja2=2.10.3=py_0
  - jmespath=0.9.4=py_0
  - jpeg=9c=h14c3975_1001
  - jsonschema=3.2.0=py36_0
  - kiwisolver=1.1.0=py36hc9558a2_0
  - krb5=1.16.4=h2fd8d38_0
  - libblas=3.8.0=14_openblas
  - libcblas=3.8.0=14_openblas
  - libclang=9.0.0=default_hde54327_4
  - libcroco=0.6.13=h8d621e5_0
  - libcurl=7.65.3=hda55be3_0
  - libdeflate=1.2=h516909a_1
  - libedit=3.1.20170329=hf8c457e_1001
  - libffi=3.2.1=he1b5a44_1006
  - libgcc=7.2.0=h69d50b8_2
  - libgcc-ng=9.2.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_2
  - libiconv=1.15=h516909a_1005
  - liblapack=3.8.0=14_openblas
  - libllvm9=9.0.0=hc9558a2_3
  - libopenblas=0.3.7=h5ec1e0e_6
  - libpng=1.6.37=hed695b0_0
  - libprotobuf=3.11.2=h8b12597_0
  - librsvg=2.46.4=h33a7fed_0
  - libssh2=1.8.2=h22169c7_2
  - libstdcxx-ng=9.2.0=hdf63c60_0
  - libtiff=4.1.0=hc3755c2_1
  - libtool=2.4.6=h14c3975_1002
  - libuuid=2.32.1=h14c3975_1000
  - libwebp=1.0.2=hf4e8a37_4
  - libxcb=1.13=h14c3975_1002
  - libxkbcommon=0.9.1=hebb1f50_0
  - libxml2=2.9.10=hee79883_0
  - lz4-c=1.8.3=he1b5a44_1001
  - lzstring=1.0.4=py_1001
  - markdown=3.1.1=py_0
  - markupsafe=1.1.1=py36h516909a_0
  - matplotlib=2.2.4=py36_2
  - matplotlib-base=2.2.4=py36h250f245_2
  - more-itertools=8.0.2=py_0
  - mosdepth=0.2.6=hfb13731_0
  - multidict=4.6.1=py36h516909a_0
  - multiqc=1.8=py_1
  - ncurses=6.1=hf484d3e_1002
  - networkx=2.1=py36_0
  - nspr=4.24=he1b5a44_0
  - nss=3.47=he751ad9_0
  - numpy=1.17.3=py36h95a1406_0
  - openjdk=8.0.192=h14c3975_1003
  - openjpeg=2.3.1=h981e76c_3
  - openssl=1.1.1d=h516909a_0
  - pandas=0.25.3=py36hb3f55d8_0
  - pango=1.42.4=ha030887_1
  - paramiko=2.7.1=py36_0
  - pcre=8.43=he1b5a44_0
  - perl=5.26.2=h516909a_1006
  - pip=19.3.1=py36_0
  - pixman=0.38.0=h516909a_1003
  - pkg-config=0.29.2=h516909a_1006
  - prettytable=0.7.2=py_3
  - protobuf=3.11.2=py36he1b5a44_0
  - psutil=5.6.7=py36h516909a_0
  - pthread-stubs=0.4=h14c3975_1001
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.19=py36_1
  - pygments=2.5.2=py_0
  - pygraphviz=1.3.1=py36_0
  - pynacl=1.3.0=py36h516909a_1001
  - pyopenssl=19.1.0=py36_0
  - pyparsing=2.4.5=py_0
  - pyqt=5.12.3=py36hcca6a23_1
  - pyrsistent=0.15.6=py36h516909a_0
  - pysftp=0.2.9=py36_0
  - pysocks=1.7.1=py36_0
  - python=3.6.7=h357f687_1006
  - python-dateutil=2.8.1=py_0
  - python-irodsclient=0.7.0=py_0
  - pytz=2019.3=py_0
  - pyyaml=5.2=py36h516909a_0
  - qt=5.12.5=hd8c4c69_1
  - ratelimiter=1.2.0=py36_1000
  - readline=8.0=hf8c457e_0
  - requests=2.22.0=py36_1
  - rsa=3.1.4=py36_0
  - s3transfer=0.2.1=py36_0
  - samtools=1.9=h10a08f8_12
  - setuptools=42.0.2=py36_0
  - simplejson=3.8.1=py36_0
  - six=1.13.0=py36_0
  - smmap2=2.0.5=py_0
  - snakemake=5.9.1=0
  - snakemake-minimal=5.9.1=py_0
  - spectra=0.0.11=py_1
  - sqlite=3.30.1=hcee41ef_0
  - tk=8.6.10=hed695b0_0
  - tornado=6.0.3=py36h516909a_0
  - typing_extensions=3.7.4.1=py36_0
  - urllib3=1.25.7=py36_0
  - wheel=0.33.6=py36_0
  - wrapt=1.11.2=py36h516909a_0
  - xmlrunner=1.7.7=py_0
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.9=h516909a_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxpm=3.5.13=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-libxt=1.1.5=h516909a_1003
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.4=h14c3975_1001
  - yaml=0.2.2=h516909a_1
  - yarl=1.3.0=py36h516909a_1000
  - zipp=0.6.0=py_0
  - zlib=1.2.11=h516909a_1006
  - zstd=1.4.4=h3b9ef0a_1
  - pip:
    - pyqt5-sip==4.19.18
    - pyqtwebengine==5.12.1
prefix: /home/groups/carilee/software/anaconda3/envs/ngs-pipeline

